# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: smoky.dev
email: weeyum@smoky.dev
description: >- # this means to ignore newlines until "baseurl:"
  A blog about smoking meats
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://smoky.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _weeyum_
github_username:  weeyum
og_image: /assets/images/mobile-barbeque-smoker-in-use.jpeg
tags:
  - smoker
  - pellet grills
  - automation
  - smoking
  - recteq
  - rectec
  - rt-590
# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

analytics:
  provider: "google"
  google:
    tracking_id: UA-192130370-1

author:
  name             : "William Li"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Software Engineer"
  location         : "Los Angeles, CA"
  email            : weeyum@smoky.dev
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_weeyum_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/weeyum"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/_weeyum_"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_weeyum_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/weeyum"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/_weeyum_"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - assets/
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
